const theme={
    color:{
        green:'#00D4Ac',
        red:'#F66D68',
        blue:'#58B9FF',
        white:'#ffffff',
        light_gray:'#f7f7f7',
        dark_gray:'#8e8e8e',
        gray:'#d9d9d9',
        black:'#3a3a3a'
    },
    font:{
        h1:{
            weight:'Bold',
            size:'32px',
        },
        h2:{
            weight:'Bold',
            size:'28px',
        },
        h3:{
            weight:'Bold',
            size:'24px',
        },
        sub_head:{
            weight:'Bold',
            size:'22px',
        },
        body:{
            weight:'Medium',
            size:'18px',
        },
        caption:{
            weight:'Medium',
            size:'14px',
        }
    },
    size:{
        input:{
            width:'300px',
            height:'60px'
        },
        icon:{
            width:'24px',
            height:'24px'
        },
        big_btn:{
            width:'300px',
            height:'300px'
        },
        small_btn:{
            width:'120px',
            height:'60px'
        }
    },
    radius:{
        main:'10px',
        selector:'10px',
        modal:'25px'
    },
    shadow:{
        main:{
            color:'#8e8e8e',
            transparent:'0.25'
        },
        selector:{
            color:'#3a3a3a',
            transparent:'0.25'
        },
        modal:{
            color:'#8e8e8e',
            transparent:'0.25'
        }
    }
}

export default theme;